#!/usr/bin/env python3

import argparse
import csv
import time
from bisect import bisect_left, bisect_right
from collections import Counter
from datetime import date, datetime
from typing import Iterator, TextIO

parser = argparse.ArgumentParser(description="Most active cookie")
parser.add_argument("cookie_log", help="Cookie log file") # Positional
parser.add_argument("-d", "--date", help="Date") # Flag

args = parser.parse_args()
# print(f"Hello {args.cookie_log} {args.date}")

def _parse_utc_date(date_str: str) -> date:
    try:
        return date.fromisoformat(date_str)  # expects YYYY-MM-DD[time+offeset]
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"Invalid date '{date_str}'. Expected format: YYYY-MM-DD or YYYY-MM-DD[time][offset]"
        ) from exc

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Most active cookie")
    parser.add_argument("cookie_log", help="Path to cookie log CSV file")
    parser.add_argument("-d", "--date", required=True, type=_parse_utc_date)
    return parser

def str_to_date(timestamp: str) -> date:
    return datetime.fromisoformat(timestamp).date()

def get_day_cookies_linear_scan_stop_early(cookie_log_reader : Iterator[list[str]], valid_date : date) -> list[str]:
    cookie_counter = Counter()
    for cookie, timestamp in cookie_log_reader:
        current_date = str_to_date(timestamp)
        if current_date < valid_date:
            break
        elif current_date == valid_date:
            cookie_counter[cookie] += 1
    
    max_count = max(cookie_counter.values(), default=0)
    valid_cookies = [cookie for cookie, cnt in cookie_counter.items() if cnt == max_count]
    return valid_cookies
    
def get_day_cookies(cookie_log_reader : Iterator[list[str]], date : datetime.date, testing=False) -> list[str]:
    if not testing:
        return get_day_cookies_linear_scan_stop_early(cookie_log_reader, date)
    
    # testing code here


def get_reader(file : TextIO) -> Iterator[list[str]]:
    reader = csv.reader(file)
    header = next(reader) # skip header (assume the file is not empty)
    return reader 

def main():
    parser = build_parser()
    args = parser.parse_args()
    with open(args.cookie_log, 'r') as file:
        reader = get_reader(file)
        active_cookies = get_day_cookies(reader, args.date)
        output = "\n".join(active_cookies) if active_cookies else f"No cookies on {args.date}"
    print(output)

if __name__ == "__main__":
    raise SystemExit(main())